/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package gr.uoa.di.pcomp.sampleAvro;

import org.apache.avro.specific.SpecificData;

@SuppressWarnings("all")
/** A sample Avro file for testing */
@org.apache.avro.specific.AvroGenerated
public class SampleAvro extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = 3515883825901264123L;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"SampleAvro\",\"namespace\":\"gr.uoa.di.pcomp.sampleAvro\",\"doc\":\"A sample Avro file for testing\",\"fields\":[{\"name\":\"time\",\"type\":\"long\",\"doc\":\"Time elapsed since the Unix epoch\",\"unit\":\"ms\"},{\"name\":\"value\",\"type\":\"double\",\"doc\":\"Sample value\"}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }
  /** Time elapsed since the Unix epoch */
   public long time;
  /** Sample value */
   public double value;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public SampleAvro() {}

  /**
   * All-args constructor.
   * @param time Time elapsed since the Unix epoch
   * @param value Sample value
   */
  public SampleAvro(java.lang.Long time, java.lang.Double value) {
    this.time = time;
    this.value = value;
  }

  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call.
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return time;
    case 1: return value;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  // Used by DatumReader.  Applications should not call.
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: time = (java.lang.Long)value$; break;
    case 1: value = (java.lang.Double)value$; break;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  /**
   * Gets the value of the 'time' field.
   * @return Time elapsed since the Unix epoch
   */
  public java.lang.Long getTime() {
    return time;
  }

  /**
   * Sets the value of the 'time' field.
   * Time elapsed since the Unix epoch
   * @param value the value to set.
   */
  public void setTime(java.lang.Long value) {
    this.time = value;
  }

  /**
   * Gets the value of the 'value' field.
   * @return Sample value
   */
  public java.lang.Double getValue() {
    return value;
  }

  /**
   * Sets the value of the 'value' field.
   * Sample value
   * @param value the value to set.
   */
  public void setValue(java.lang.Double value) {
    this.value = value;
  }

  /**
   * Creates a new SampleAvro RecordBuilder.
   * @return A new SampleAvro RecordBuilder
   */
  public static gr.uoa.di.pcomp.sampleAvro.SampleAvro.Builder newBuilder() {
    return new gr.uoa.di.pcomp.sampleAvro.SampleAvro.Builder();
  }

  /**
   * Creates a new SampleAvro RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new SampleAvro RecordBuilder
   */
  public static gr.uoa.di.pcomp.sampleAvro.SampleAvro.Builder newBuilder(gr.uoa.di.pcomp.sampleAvro.SampleAvro.Builder other) {
    return new gr.uoa.di.pcomp.sampleAvro.SampleAvro.Builder(other);
  }

  /**
   * Creates a new SampleAvro RecordBuilder by copying an existing SampleAvro instance.
   * @param other The existing instance to copy.
   * @return A new SampleAvro RecordBuilder
   */
  public static gr.uoa.di.pcomp.sampleAvro.SampleAvro.Builder newBuilder(gr.uoa.di.pcomp.sampleAvro.SampleAvro other) {
    return new gr.uoa.di.pcomp.sampleAvro.SampleAvro.Builder(other);
  }

  /**
   * RecordBuilder for SampleAvro instances.
   */
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<SampleAvro>
    implements org.apache.avro.data.RecordBuilder<SampleAvro> {

    /** Time elapsed since the Unix epoch */
    private long time;
    /** Sample value */
    private double value;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(gr.uoa.di.pcomp.sampleAvro.SampleAvro.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.time)) {
        this.time = data().deepCopy(fields()[0].schema(), other.time);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.value)) {
        this.value = data().deepCopy(fields()[1].schema(), other.value);
        fieldSetFlags()[1] = true;
      }
    }

    /**
     * Creates a Builder by copying an existing SampleAvro instance
     * @param other The existing instance to copy.
     */
    private Builder(gr.uoa.di.pcomp.sampleAvro.SampleAvro other) {
            super(SCHEMA$);
      if (isValidValue(fields()[0], other.time)) {
        this.time = data().deepCopy(fields()[0].schema(), other.time);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.value)) {
        this.value = data().deepCopy(fields()[1].schema(), other.value);
        fieldSetFlags()[1] = true;
      }
    }

    /**
      * Gets the value of the 'time' field.
      * Time elapsed since the Unix epoch
      * @return The value.
      */
    public java.lang.Long getTime() {
      return time;
    }

    /**
      * Sets the value of the 'time' field.
      * Time elapsed since the Unix epoch
      * @param value The value of 'time'.
      * @return This builder.
      */
    public gr.uoa.di.pcomp.sampleAvro.SampleAvro.Builder setTime(long value) {
      validate(fields()[0], value);
      this.time = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'time' field has been set.
      * Time elapsed since the Unix epoch
      * @return True if the 'time' field has been set, false otherwise.
      */
    public boolean hasTime() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'time' field.
      * Time elapsed since the Unix epoch
      * @return This builder.
      */
    public gr.uoa.di.pcomp.sampleAvro.SampleAvro.Builder clearTime() {
      fieldSetFlags()[0] = false;
      return this;
    }

    /**
      * Gets the value of the 'value' field.
      * Sample value
      * @return The value.
      */
    public java.lang.Double getValue() {
      return value;
    }

    /**
      * Sets the value of the 'value' field.
      * Sample value
      * @param value The value of 'value'.
      * @return This builder.
      */
    public gr.uoa.di.pcomp.sampleAvro.SampleAvro.Builder setValue(double value) {
      validate(fields()[1], value);
      this.value = value;
      fieldSetFlags()[1] = true;
      return this;
    }

    /**
      * Checks whether the 'value' field has been set.
      * Sample value
      * @return True if the 'value' field has been set, false otherwise.
      */
    public boolean hasValue() {
      return fieldSetFlags()[1];
    }


    /**
      * Clears the value of the 'value' field.
      * Sample value
      * @return This builder.
      */
    public gr.uoa.di.pcomp.sampleAvro.SampleAvro.Builder clearValue() {
      fieldSetFlags()[1] = false;
      return this;
    }

    @Override
    public SampleAvro build() {
      try {
        SampleAvro record = new SampleAvro();
        record.time = fieldSetFlags()[0] ? this.time : (java.lang.Long) defaultValue(fields()[0]);
        record.value = fieldSetFlags()[1] ? this.value : (java.lang.Double) defaultValue(fields()[1]);
        return record;
      } catch (Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  private static final org.apache.avro.io.DatumWriter
    WRITER$ = new org.apache.avro.specific.SpecificDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  private static final org.apache.avro.io.DatumReader
    READER$ = new org.apache.avro.specific.SpecificDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

}
